/**
 * Shared constants used across the app.
 */

export const PRODUCT_CATEGORIES = [
  "Lightings & Electrical",
  "Panels",
  "Wallpaper",
  "Doors",
  "Walls",
  "Cement",
  "Steel & Iron",
  "Tiles & Flooring",
  "Paints",
  "Roofing & Ceiling",
  "Smart Home",
  "Furniture",
  "Plumbing",
  "Aggregates",
  "Wood & Timber",
  "Automobile",
  "Laundromat",
] as const;

export type ProductCategory = (typeof PRODUCT_CATEGORIES)[number];

/* ─── Artisan skill categories & skills (from Global Artisan Skills Masterlist) ── */

export interface ArtisanSkillCategory {
  id: string;
  name: string;
  skills: string[];
}

export const ARTISAN_SKILL_CATEGORIES: ArtisanSkillCategory[] = [
  {
    id: "carpentry",
    name: "Carpentry & Woodworking",
    skills: [
      "Furniture Making",
      "Custom Cabinetry",
      "Wooden Doors & Window Frames",
      "Decorative Wooden Wall Panels",
      "Crown Moldings & Wainscoting",
      "Wooden Ceiling Beams & Coffered Ceilings",
      "Parquet & Hardwood Flooring",
      "Hardwood Flooring Installation",
      "Carved Wood Sculptures",
      "Tongue-and-Groove Wood Planks",
      "Beamed Ceilings",
      "Decorative Wooden Lattice & Mashrabiya Panels",
      "Wooden Acoustic Ceiling Panels",
    ],
  },
  {
    id: "masonry",
    name: "Masonry, Stone & Concrete Work",
    skills: [
      "Bricklaying & Block Work",
      "Stone Wall Construction",
      "Marble, Granite & Limestone Sculpting",
      "Concrete Finishing & Polishing",
      "Decorative Stamped Concrete",
      "3D Printed Concrete Walls & Panels",
      "Tiling (Ceramic, Porcelain, Stone)",
      "Mosaic Tile Walls & Floors",
      "Stone Veneer & Brick Veneer Walls",
      "Fireplace Building",
    ],
  },
  {
    id: "metalwork",
    name: "Metalwork & Fabrication",
    skills: [
      "Iron Gates, Railings & Balconies",
      "Decorative Metal Panels & Screens",
      "Steel & Aluminum Structure Fabrication",
      "Wrought Iron Furniture",
      "Brass, Copper & Bronze Fixtures",
      "Metal Ceiling Panels",
      "Perforated Metal Acoustic Ceilings",
      "Welding, Soldering & Engraving",
      "Decorative Lighting Frames",
    ],
  },
  {
    id: "painting",
    name: "Painting & Finishing",
    skills: [
      "Interior Wall Painting",
      "Exterior Painting",
      "Faux Finishes (Marble, Stone, Wood, Metallic)",
      "Trompe-l'oeil / 3D Wall Painting",
      "Murals & Frescoes",
      "Stenciling & Patterned Painting",
      "Ombre / Gradient Painting",
      "Decorative Plaster / Stucco Walls",
      "Venetian / Polished Plaster Finishes",
      "Ceiling Painting & Faux Finishes",
    ],
  },
  {
    id: "ceilings",
    name: "Ceilings",
    skills: [
      "Gypsum False Ceiling Installation",
      "POP Decorative Ceilings",
      "PVC & Fiberboard Ceilings",
      "Suspended / Drop Ceilings",
      "Stretch Ceilings (PVC/Fabric)",
      "Cove & Multi-Layered Ceilings",
      "Coffered & Beamed Wooden Ceilings",
      "Tin / Aluminum Embossed Panels",
      "Acoustic Ceilings",
      "Integrated Lighting in Ceilings",
      "Ceiling Roses, Medallions & Moldings",
      "Ceiling Murals & Stenciling",
      "3D Printed Decorative Panels",
      "Smart Ceiling Integration",
      "Eco-Friendly Ceilings",
    ],
  },
  {
    id: "wall-decoration",
    name: "Wall Decoration",
    skills: [
      "Standard Wall Painting",
      "Faux Wall Finishes",
      "Stenciling & Patterned Painting",
      "Trompe-l'oeil & Murals",
      "Venetian / Polished Plaster Walls",
      "Wallpaper Installation",
      "Panoramic & Mural Wallpaper",
      "3D Textured Wallpaper Installation",
      "Metallic & Reflective Wallpaper",
      "Wall Decals & Removable Stickers",
      "Wooden Wall Paneling",
      "Tongue-and-Groove Wall Planks",
      "Wainscoting / Beadboard",
      "Stone / Brick Veneer Walls",
      "Ceramic / Porcelain Tile Accent Walls",
      "Glass & Mirror Walls",
      "Metal Decorative Walls",
      "Acoustic Wall Panels",
      "Mosaic Tile Art Walls",
      "Fabric Wall Coverings / Tapestries",
      "Cork Wall Installation",
      "Chalkboard / Writable Walls",
      "Magnetic / Pegboard Walls",
      "Resin / Epoxy Decorative Walls",
      "Reclaimed Wood Feature Walls",
      "Eco-Friendly Plaster / Clay Walls",
      "Built-in Shelves & Niches",
      "Wall-Mounted Lighting & Sconces",
      "HVAC & Pipe Concealment Behind Panels",
      "Smart Walls (LED Screens, Projection)",
    ],
  },
  {
    id: "flooring",
    name: "Flooring & Tiling",
    skills: [
      "Hardwood, Bamboo, Laminate & Vinyl Flooring",
      "Parquet & Engineered Wood Floors",
      "Ceramic, Porcelain & Mosaic Tiles",
      "Marble & Granite Floors",
      "Stone Paving & Cobblestone",
      "Carpeting & Rugs",
      "Epoxy Resin Floors",
    ],
  },
  {
    id: "electrical",
    name: "Electrical & Lighting",
    skills: [
      "Electrical Wiring Installation",
      "Decorative & Functional Lighting",
      "Pendant & Chandelier Installation",
      "Outdoor / Landscape Lighting",
      "Smart Home Electrical Systems",
      "LED Strip & Recessed Lighting",
      "Integrated Audio Systems",
    ],
  },
  {
    id: "plumbing",
    name: "Plumbing & Water Features",
    skills: [
      "Pipe Installation & Bathroom/Kitchen Fittings",
      "Water Feature Construction",
      "Rainwater Harvesting & Irrigation",
      "Concealed Plumbing Behind Walls & Panels",
    ],
  },
  {
    id: "roofing",
    name: "Roofing & Exterior Work",
    skills: [
      "Roof Framing & Trusses",
      "Tile, Slate, Metal & Thatch Roofs",
      "Waterproofing & Insulation",
      "Gutters, Fascias & Soffits",
      "Exterior Cladding",
    ],
  },
  {
    id: "landscaping",
    name: "Landscaping & Outdoor Decor",
    skills: [
      "Garden & Patio Design",
      "Decks, Pergolas & Gazebos",
      "Outdoor Furniture Crafting",
      "Paving & Hardscaping",
      "Fences & Gates",
      "Pools & Water Features",
      "Lawn Design & Turf Installation",
      "Rock Gardens & Zen Gardens",
      "Xeriscaping (Low-Water Landscaping)",
      "Sustainable / Native Plant Landscaping",
    ],
  },
  {
    id: "curtains",
    name: "Curtains & Window Treatments",
    skills: [
      "Fabric Selection for Curtains",
      "Measuring & Cutting Curtain Fabric",
      "Sewing & Pleating Techniques",
      "Curtain Lining & Insulation",
      "Decorative Trims, Tassels & Fringes",
      "Curtain Types (Rod Pocket, Tab Top, Eyelet, Ripple Fold, Roman, Roller, Venetian)",
      "Ceiling or Wall-Mounted Curtain Track Installation",
      "Motorized / Automated Curtain Systems",
      "Tiebacks, Holdbacks & Rings Installation",
      "Layering Curtains with Sheers & Drapes",
    ],
  },
  {
    id: "bathroom-kitchen",
    name: "Toilet, Bathroom & Kitchen Solutions",
    skills: [
      "Pipe & Water Supply Installation",
      "Drainage & Waste Pipe Systems",
      "Toilet Installation",
      "Bidet Installation",
      "Bathtub Installation",
      "Shower Tray / Cubicle Installation",
      "Faucet & Tap Installation",
      "Water Heater / Geyser Installation",
      "Bathroom Tiling & Waterproofing",
      "Kitchen Tiling & Backsplash Installation",
      "Bathroom Vanity & Cabinet Installation",
      "Kitchen Cabinetry & Countertop Installation",
      "Shelving & Niches for Wet Areas",
      "Fixtures & Hardware Installation",
      "Bathroom & Kitchen Lighting",
      "Ventilation & Exhaust Fan Installation",
      "Smart & Eco-Friendly Water Solutions",
      "Heated Floors & Towel Rails",
      "Luxury Installations (Jacuzzi, Steam Showers)",
      "Integrated Appliances (Dishwasher, Oven, Cooktop)",
    ],
  },
  {
    id: "acp",
    name: "Aluco Board / ACP Applications",
    skills: [
      "Material Knowledge & Panel Handling",
      "Measuring & Cutting ACP Panels",
      "Drilling & Punching for Fasteners",
      "Edge Finishing & Trimming",
      "Surface Cleaning & Color Matching",
      "Exterior ACP Cladding & Ventilated Facades",
      "Hidden Fastener Installation",
      "Rain-Screen Panel Installation",
      "Expansion Joint Planning & Sealing",
      "Curved or Angled ACP Panels",
      "Interior ACP False Ceilings & Wall Panels",
      "Kitchen & Bathroom Feature Panels",
      "Partition Walls with ACP",
      "Decorative CNC-Cut ACP Panels",
      "Etching, Engraving & Laminated Finishes",
      "Acoustic ACP Panels",
      "Fire-Retardant ACP Panels",
      "Backlit or LED ACP Integration",
      "Mixed Material Integration (Glass, Wood, Metal)",
      "Maintenance & Panel Replacement",
    ],
  },
  {
    id: "cleaning",
    name: "Industrial Cleaning",
    skills: [
      "Commercial Floor Cleaning & Polishing",
      "High-Rise Window Cleaning",
      "Pressure Washing Exterior Surfaces",
      "Kitchen & Bathroom Deep Cleaning",
      "Dust & Debris Removal from Construction Sites",
      "Sanitation & Chemical Cleaning",
      "Graffiti Removal",
      "Industrial Equipment Cleaning",
      "Carpet & Upholstery Cleaning",
      "HVAC Duct & Vent Cleaning",
    ],
  },
  {
    id: "traditional",
    name: "Regional & Traditional Styles",
    skills: [
      "European: Fresco Murals, Coffered Ceilings, Marble, Ornate Cabinetry",
      "Middle Eastern: Mashrabiya, Geometric Plaster, Mosaic Tiles",
      "Asian: Bamboo Panels, Tatami, Minimalist Design",
      "African: Carved Wood, Clay Plaster, Mud Walls, Natural Stone",
      "South American: Adobe, Clay, Colorful Tiles, Tropical Gardens",
      "Moroccan: Zellige Tiles, Mosaic Water Features, Courtyard Fountains",
      "Indian: Hand-Carved Stone, Jali Screens, Brocade Curtains",
    ],
  },
  {
    id: "modern",
    name: "Modern & Innovative Techniques",
    skills: [
      "Smart Home Integration",
      "Automated Curtains & Blinds",
      "LED Strip & Backlit Feature Panels",
      "3D Printed Panels & Furniture",
      "Eco-Friendly Materials (Reclaimed Wood, Bamboo, Hempcrete)",
      "Solar-Powered Water Heaters",
      "Sensor-Activated Faucets, Toilets & Lights",
      "Waterproof & UV-Blocking Outdoor Systems",
      "Permeable Paving & Sustainable Hardscaping",
      "Modular Furniture & Partition Systems",
    ],
  },
  {
    id: "tools",
    name: "Tools & Technical Skills",
    skills: [
      "Measuring, Leveling & Layout Precision",
      "Cutting & Shaping (Wood, Plaster, Metal, PVC, ACP)",
      "Sanding, Painting, Polishing & Finishing",
      "Pattern Transfer for Murals/Stencils",
      "Safe Lifting & Panel Installation",
      "Electrical & Plumbing Integration Behind Walls/Ceilings",
      "CNC, Router, Saw & Drill Operation",
      "Scaffolding & Lifts for High Work",
      "Sealant, Silicone & Fastener Application",
      "Multi-Material Integration (Glass, Metal, Stone, Wood)",
    ],
  },
  {
    id: "acoustic",
    name: "Acoustic & Functional Integration",
    skills: [
      "Acoustic Wall & Ceiling Panels",
      "Fabric-Wrapped Soundproof Panels",
      "Modular Ceiling/Wall Systems for Offices",
      "Thermal Insulation Walls & Ceilings",
      "Concealed Smart Wiring, Lighting & Speakers",
      "Heated Floors & Towel Rails Integration",
      "Smart Mirrors & Appliance Integration",
      "Water Recycling & Greywater Systems",
    ],
  },
];

/** Flat list of all artisan skill names */
export const ALL_ARTISAN_SKILLS = ARTISAN_SKILL_CATEGORIES.flatMap((c) => c.skills);

export const NAIRA = new Intl.NumberFormat("en-NG", {
  style: "currency",
  currency: "NGN",
  minimumFractionDigits: 0,
  maximumFractionDigits: 0,
});

export const formatNaira = (amount: number) => NAIRA.format(amount);
